sudo: required
services: 
  - docker

before_install:
  - docker build -t sushmita/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true sushmita/frontend npm run test -- -- coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "frontend"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-wesr-2-306476627547"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"